apiVersion: v1
kind: ConfigMap
metadata:
  name: import-net-scripts #Change this name here and in the statefulset's yaml, example: name: pifod-mysql-scripts configMap: name: import-pifod-scripts
  namespace: net-haep #NAMESPACE
data: #Change the password for user password, the password must be the same in the docker file environment variable
  creatDataBase.sql: |
    CREATE DATABASE IF NOT EXISTS proyecto;
    USE proyecto;
    CREATE USER 'user'@'%' IDENTIFIED BY 'psswrd-p1f0dsd-user!'; 
    GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
    CREATE USER 'read'@'%' IDENTIFIED BY '$read-secure-psswrd&';
    GRANT SELECT ON proyecto.* TO 'read'@'%';
    CREATE USER 'write'@'%' IDENTIFIED BY '=access-for-write-user##';
    GRANT SELECT, INSERT, UPDATE, DELETE ON proyecto.* TO 'write'@'%';
    FLUSH PRIVILEGES;