apiVersion: v1
kind: Namespace
metadata:
  name: net-haep #NAMESPACE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: net-mysql-pvc #Mysql volume name
  namespace: net-haep #NAMESPACE
spec:
  storageClassName: nfs-csi-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-content-pvc  #doesn't need a change
  namespace: net-haep #NAMESPACE
spec:
  storageClassName: nfs-csi-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-content-pvc #doesn't need a change
  namespace: net-haep #NAMESPACE
spec:
  storageClassName: nfs-csi-2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi